### ISSUE TITLE
Output of compiled CSS SASS file is empty

### ISSUE THREAD

**Issue by smartmeter** [madskristensen/WebCompiler#184]
In the current build the css output is empty files for both min and regular.

Looks like others have this issue too from the link here on (Oct  26 2015, Jan 4 2016) https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c

**Comment by matthewpavkov** [comment]
@smartmeter You're going to need to provide more information. How can this issue be reproduced? What have you tried doing to resolve it? Which build of Web Compiler are you using (1.10.300)?

**Comment by smartmeter** [comment]
Hi, I'm using 

  *    **Webompiler** 1.10.300 from Jan 22/16 build
  *    **W Essentials** 1.0.203  Jan  6/16

So, they are both the latest build. 

Steps:
The steps are per instruction you've listed on https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c . I created a new folder in Content calls SASSTEST, then copied the files there.

Right clicked on the variables SASS  file and selected compile.

Next after verifying compilerconfig.json was created in the root of the project.

I looked at the target output folder

Inside task runner I hit run, it gave me feedback that it was completed, and created the output files, which were empty when I opened them

I also tried to enable compile on build and other options as per instructions but still empty.

**Comment by manualshifter** [comment]
:-1: I have the same exact problem

Its been there since the last 2 releases. Either the documentation steps are wrong or the webcompiler has a bug.

**Comment by novinaw** [comment]
Same/similar problem.  it just stopped compiling since the last version a few days ago.   Both at save and force recompile (but I don't have an empty file, I just have the same css file I had since the last successful generated (maybe 4 days ago)

**Comment by manualshifter** [comment]
They really need to address this!

**Comment by madskristensen** [comment]
Can someone help out by posting a simple repro? I can't repro this.

@manualshifter Who are _they_ and what do you think _they_ need to do?

**Comment by sk5** [comment]
Scenario: multiple "master" scss files that include many imports. Saving any of the imports should recompile all effected bundles

1. Saving the scss file for a specific bundle creates css bundle. ex: saving styles.scss makes styles.css 
2. saving compilerconfig.json creates ALL bundles of effected scss files
3. saving any scss file shows a message in the bottom of VS of "Compiled Successfully" but nothing really happens
4. Right clicking on the bundle in the task runner explorer and choosing run does nothing

Here is a video. For now we are keeping compilerconfig.json open and just saving it every time we edit any scss file. 

http://screencast.com/t/E6L6QjHbRsKa

**Comment by matthewpavkov** [comment]
@sk5 Can you reliably reproduce the issue? If so, post a solution to test with here. I've been trying to reproduce the issue, but I can't. However, I've seen it happen on one of my coworkers computers as recently as this morning.

**Comment by ericdc1** [comment]
@matthewpavkov I work with @sk5 and we are able to repro this in several machines exactly as shown in the video. Windows 10, VS15 Pro, latest Web Essentials, latest Web Compiler.

**Comment by matthewpavkov** [comment]
@ericdc1 Yeah, I watched the video. That looks like the same problem I'm seeing over here. However, I can't reproduce it reliably. In fact, it hasn't even happened to me, only to a few of my coworkers. Does the non-compiling happen every time for you? Can you strip down your solution and post it here? If we can reproduce it, we can probably figure out what's going on.

**Comment by ericdc1** [comment]
We figured this out at least for our case. 

We have styles.scss that imports a filed called "_settings.variables.scss" like this:

@import "settings.variables";

This seems to be valid syntax as saving compilerconfig produces the styles.css file. With this syntax, saving _settings.variables.scss does not trigger updating the styles.css though.

We changed the import to this and now saving the _settings.variables.scss now triggers recompilation of the css files. 

@import "_settings.variables.scss";

It seems the magic saving trigger of any .scss file does not work when we use the shorthand imports language. It has to be the exact file name to work.

**Comment by madskristensen** [comment]
This should now be fixed. Please help verify the fix in the CI build version 1.10.302 that is ready in a couple of minutes here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by madskristensen** [comment]
Anyone try it yet?

**Comment by sk5** [comment]
Hey Mads! I have and it works like a champ. Hopefully this solves the issues other people who reported this have as well. I imagine some people were reference files like we were. We appreciate the quick response!

**Comment by smartmeter** [comment]
Hi, I want to re-open this, I have been testing it (but it was closed)

I reported this problem, but it looks like the same problem is still there intermittently. So I will try to explain :)

- [ ] the partial `_variables.scss` compiles fine, to the _Shift + ALT + Q_ the _variables.scss .
- [ ] The second step where -> `style.scss`  should pick it up -> **compile and -> overwrite the  existing style.css does not work**. The task runner also does not show the style.scss in the compiler configuration even after adding it with right click.

I would like to understand _if you're expecting the developer to perform a different second step_... can you please clarify... what you're expecting us to do so that the style.css gets over written - the documentation does not call this out

thanks

**Comment by smartmeter** [comment]
> C:\..\VisualStudio\14.0\Extensions\4uccawr3.krg\WebCompiler.exe "c:\MadsWc\compilerconfig.json"  *.SCSS
	
Processing Content/_variables.scss
  Compiled
  Minified
	
`Process terminated with code 1.
It's not clear which file to import for '@import "variables"'.
Candidates:`
 `_variables.scss` 
 `_variables.css`

// looks like its confused between which file to pick for import - is there a way to narrow this down, or configure it!
