### ISSUE TITLE
Can't compile nested less files with Web Compiler 2015

### ISSUE THREAD

**Issue by Nikkelmann** [madskristensen/WebCompiler#185]
http://stackoverflow.com/questions/31345130/cant-compile-nested-less-files-with-web-compiler-2015

I also have the same problem as described in the SO question.

The less compiler does not include the importet less files and does not use the variables inside.

The version i'm using is 1.10.300

**Comment by andreasnylin** [comment]
I have the same problem. VS Professional 2015 Update 1 and Web Compiler 1.10.300

Included files does not trigger compilation of the main file on save.

**Comment by jellyisnotporous** [comment]
Currently experiencing the same problem as @andreasnylin, VS Professional 2015, Web Compiler 1.10.300.

Compile on save no longer works, although VS displays "Compiled successfully". No errors displayed although was previously displaying an error with the compilerconfig.json.

Forcing compile (Web Compiler > Recompile all files) does work.

**Comment by matthewpavkov** [comment]
My team may be experiencing something similar to this for SASS/SCSS files. They've reported that at times, saving from one of the SASS/SCSS files will trigger the compiling (you see the message in the bottom-left corner) and then VS will show you "Compiled successfully" but the compiled CSS file does not update (the changes in SASS won't be in the compiled CSS). However, when this happens, if they go to the main SASS file (the one which is set up to be compiled into CSS) and save from that file, then things always work.

I have not yet been able to reproduce this yet. I'll report back when I can. This seems to be a new issue, but I'm not certain yet.

**Comment by Luuk1983** [comment]
I'm experiencing exactly the same problem: when editing and saving 'partial' scss files, the main scss file doesn't get recompiled. This makes this plugin completely useless since I'm required after each change in the 'partial' scss files to recompile the main css manually (by saving it or use the recompile option). This issue is present in version 1.10.300 and 1.10.301. For now I'm using an old version, but that one has it's limits as well. I hope it will be fixed very soon!

**Comment by madskristensen** [comment]
I cannot reproduce this issue. Can someone please help create a simple repro project I can use to debug with?

**Comment by Luuk1983** [comment]
I've created a very basic testproject. I can't add the zip I created to this message, so I've hosted it here for now: [WebCompileTest.zip](http://www.masc.nl/WebCompileTest.ZIP). In this example, when I change in css/partials/_layout.zip the background-color and save it, the css/Stylesheet.css is not updated until the css/stylesheet.scss file is recompiled by changing and saving it, or recompiling it through the menu.

I have Visual Studio 2015 with update 1 and WebCompiler 1.10.301.

**Comment by madskristensen** [comment]
@Luuk1983 Perfect, thanks for the project. I can reproduce the issue now and a fix is coming.

**Comment by madskristensen** [comment]
This should now be fixed. Please help verify the fix in the CI build version 1.10.302 that is ready in a couple of minutes here http://vsixgallery.com/extension/148ffa77-d70a-407f-892b-9ee542346862/

**Comment by madskristensen** [comment]
Anyone try it yet?

**Comment by Luuk1983** [comment]
Hi Mads,

I was just testing it when you wrote the message. The test project (which I sent you earlier) seems to work perfectly now. Thanks!

I'm not a 100% sure, but as far as I know, partial scss files are supposed to have an underscore in their names, indicating that these partial scss failes are not to be compile seperatly. scss files without underscore should be compiled. 

With this in mind, it's my humble opinion that should't be neccesary to have a json file which defines what scss files to compile because it is simple: underscore = no compile, no underscore = compile. I can't think of a reason why one wouldn't want to compile a scss file. So I'd rather have a json file which defines what scss files NOT to compile.

Just a thought though, I'm curious about other peoples opinions.

Thanks again Mads, it's a great plugin!

**Comment by madskristensen** [comment]
@Luuk1983 We had the issue back in Web Essentials 2013 where we had to add a `.weignore` file because there were scenarios where this would fall apart. I don't remember the specifics, but there was a lot of reported issues on this

**Comment by pwavg** [comment]
I still have some problems with this issue. When using Web compiler and nested less files saving a file that is referenced inside the nested source less file results in a "compiled successfully" message but the file is not processed. I created a test repro for testing purposes [(https://github.com/pwavg/WebCompilerNestedLess)]
